
project_id = "ntbkydpgjaswmwruegyl"

[api]
enabled = true
port = 54321

[functions.churn-csv-handler]
verify_jwt = true

[functions.process-csv]
verify_jwt = false

[functions.track]
verify_jwt = false
