
project_id = "ntbkydpgjaswmwruegyl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.email-inbound]
verify_jwt = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.sdk-track]
verify_jwt = false

[functions.retention-event]
verify_jwt = false
enabled = true
port = 54321

[functions.churn-csv-handler]
verify_jwt = true

[functions.process-csv]
verify_jwt = false

[functions.track]
verify_jwt = false

[functions.api-sync]
verify_jwt = false

[functions.auto-email-trigger]
verify_jwt = false
