
project_id = "ntbkydpgjaswmwruegyl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[functions.enhanced-churn-upload]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.robust-churn-processor]
verify_jwt = false

[functions.check-status]
verify_jwt = false

[functions.download-report]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-churn-report-email]
verify_jwt = false

[functions.rules-based-churn-prediction]
verify_jwt = true

[functions.generate-retention-emails]
verify_jwt = true

[functions.process-csv-audit]
verify_jwt = false
